export const CREATE_PASSWORD = "CREATE_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const DELETE_PASSWORD = "DELETE_PASSWORD";
export const GET_PASSWORD_FROM_SERVER = "GET_PASSWORD_FROM_SERVER";
